### ISSUE TITLE
BUG WITH GEOX 

### ISSUE THREAD

**Issue by MattyDev01** [91DarioDev/iplogger#3]
There is a bug with GEOX (getLocation)

put in the link together with the redirect neither works
doesn't work in every browser

**Comment by 91DarioDev** [comment]
in some browser it works while in others it doesn't.

basically the redirection should start after the user press ok to share the location but actually scenarios where the pop up is not shown are not handled and maybe handling them could fix it.
the are the lines that should be fixed https://github.com/91DarioDev/iplogger/blob/7973a51dceb2671e5ce908cbf3ccddbed48f5f1a/index.php#L75

i'll look into it as i can

**Comment by 91DarioDev** [comment]
fixed with the last two commits. reopen an issue in case of other problems
